반짝이는 버튼을 속성만으로 쓸 수 있도록 리팩토링
readable-team/readable pull request #907
Opened 2024-09-16 14:20 UTC by dolsup

2024-09-16 14:20 UTC, dolsup commented
* **#907** <a href="https://app.graphite.dev/github/pr/readable-team/readable/907?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dolsup and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-16 14:29 UTC, Seohyun-Roh requested changes

2024-09-16 14:29 UTC, Seohyun-Roh commented on packages/ui/src/components/Button.svelte
> +        borderRadius: '8px',
P2: 버튼 사이즈마다 라운드가 다르대요~~

2024-09-16 14:34 UTC, dolsup commented on packages/ui/src/components/Button.svelte
> +        borderRadius: '8px',
수정완 .  .. . !! !!

2024-09-16 14:58 UTC, Seohyun-Roh approved these changes

2024-09-17 00:41 UTC, devunt approved these changes

2024-09-17 00:46 UTC, merged